/**
 * The colour-scheme presets Appearance offers, ported from V1's `Themes/TendrilThemes.cs`.
 *
 * V1 keeps a `TendrilThemeDescriptor` per preset (id, name, description, `IsDark`, four
 * `PreviewColors` and a full Ivy `Theme`), and applies one by generating a stylesheet and handing it
 * to `client.ApplyTheme(css)`. This module keeps both decisions: the table below is those
 * descriptors verbatim, and {@link applyThemePreset} injects one `<style>` element rather than
 * writing inline styles, so the light and dark halves of a preset are both installed at once and a
 * `prefers-color-scheme` flip needs no re-application.
 *
 * The token names are `styles/tokens.css`'s, whose generated region is exactly the 25 colours V1's
 * `ThemeColors` carries. Nothing here edits that region - a preset is an override layer on top of
 * it, and the `default` preset is the absence of that layer, i.e. Tendril's own Ivy-green token set
 * rather than V1's zinc one.
 */

/** One preset's colours for one mode, keyed by the CSS custom property they set (without `--`). */
export type ThemePresetColors = Record<string, string>;

export interface ThemePreset {
  /** `TendrilThemeDescriptor.Id`, and what `config.yaml`'s `theme` key holds. */
  id: string;
  name: string;
  description: string;
  /** Whether the preset was authored dark-first. V1 uses it to pick which half to preview. */
  isDark: boolean;
  /** The four swatches Appearance draws, in V1's order: primary, secondary, accent, background. */
  previewColors: string[];
  colors: { light?: ThemePresetColors; dark?: ThemePresetColors };
  /** A theme published by a connected Team Vault rather than shipped. See the note in the module. */
  isVaultTheme?: boolean;
  vaultName?: string;
}

/** `TendrilThemes.Default.Id`, and `TendrilSettings.theme`'s default. */
export const DEFAULT_THEME_PRESET_ID = "default";

/** The id of the `<style>` element {@link applyThemePreset} owns. */
export const THEME_PRESET_STYLE_ID = "tendril-theme-preset";

/** The default preset's dark palette, which is the palette the app ships in. */
export const COMMAND_CENTER_DARK: ThemePresetColors = {
  primary: "#00cc92",
  "primary-foreground": "#04140f",
  secondary: "#161d26",
  "secondary-foreground": "#e6edf3",
  destructive: "#f06a72",
  "destructive-foreground": "#07090c",
  success: "#3fe0ae",
  "success-foreground": "#04140f",
  warning: "#f0b54a",
  "warning-foreground": "#1a1204",
  info: "#6aa1ff",
  "info-foreground": "#06101f",
  background: "#07090c",
  foreground: "#e6edf3",
  border: "#1a212b",
  input: "#232c38",
  ring: "#3fe0ae",
  muted: "#10151c",
  "muted-foreground": "#8593a1",
  accent: "#161d26",
  "accent-foreground": "#e6edf3",
  card: "#0d1117",
  "card-foreground": "#e6edf3",
  popover: "#0f141b",
  "popover-foreground": "#e6edf3",
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: DEFAULT_THEME_PRESET_ID,
    name: "Default",
    description: "Tendril's command-center theme: blue-black surfaces with the Ivy green accent",
    isDark: true,
    previewColors: ["#00cc92", "#161d26", "#0d1117", "#07090c"],
    /**
     * The app renders dark-only (see `appearance.ts`), so the dark half is the whole palette: blue-black
     * surfaces stepping up by lightness (background < card < popover < secondary), one saturated accent,
     * and status hues that differ in lightness as well as hue. Every foreground pairing clears WCAG AA.
     *
     * The light half keeps the old black primary so light-mode library stories are unchanged.
     */
    colors: {
      light: { primary: "#000000", "primary-foreground": "#ffffff" },
      dark: COMMAND_CENTER_DARK,
    },
  },
  {
    id: "ivy",
    name: "Ivy",
    description: "Tendril's own branding, with the Ivy green as the primary colour",
    isDark: false,
    previewColors: ["#00cc92", "#dfe7e3", "#f8f8f8", "#ffffff"],
    /**
     * Deliberately empty, and this is the one preset for which that is meaningful: `tokens.css` is
     * the generated Ivy design-system token set, so the *absence* of an override layer already is
     * the Ivy theme. {@link applyThemePreset} removes its `<style>` element for an empty preset,
     * which is exactly the right behaviour here.
     *
     * This is why the brand colours moved onto a preset rather than into `tokens.css`: that file's
     * palette region is generated (`pnpm sync:tokens`) and hand-editing it would be overwritten.
     */
    colors: {},
  },
  {
    id: "cupcake",
    name: "Cupcake",
    description: "Warm cream background with soft teal, pastel pink, and amber accents",
    isDark: false,
    previewColors: ["#65c3c8", "#ef9fbc", "#eeaf3a", "#faf7f5"],
    colors: {
      light: {
        primary: "#65c3c8",
        "primary-foreground": "#1d232a",
        secondary: "#ef9fbc",
        "secondary-foreground": "#1d232a",
        accent: "#eeaf3a",
        "accent-foreground": "#1d232a",
        background: "#faf7f5",
        foreground: "#291334",
        destructive: "#f87272",
        "destructive-foreground": "#000000",
        success: "#36d399",
        "success-foreground": "#1d232a",
        warning: "#fbbd23",
        "warning-foreground": "#1d232a",
        info: "#3abff8",
        "info-foreground": "#1d232a",
        border: "#e7e2df",
        input: "#f3eeea",
        ring: "#65c3c8",
        muted: "#eae5e1",
        "muted-foreground": "#5e5264",
        card: "#ffffff",
        "card-foreground": "#291334",
        popover: "#faf7f5",
        "popover-foreground": "#291334",
      },
      dark: {
        primary: "#65c3c8",
        "primary-foreground": "#1d232a",
        secondary: "#ef9fbc",
        "secondary-foreground": "#1d232a",
        accent: "#eeaf3a",
        "accent-foreground": "#1d232a",
        background: "#231a28",
        foreground: "#faf7f5",
        destructive: "#f87272",
        "destructive-foreground": "#000000",
        success: "#36d399",
        "success-foreground": "#1d232a",
        warning: "#fbbd23",
        "warning-foreground": "#1d232a",
        info: "#3abff8",
        "info-foreground": "#1d232a",
        border: "#44344e",
        input: "#2f2436",
        ring: "#65c3c8",
        muted: "#3a2d43",
        "muted-foreground": "#bbaabf",
        card: "#2f2436",
        "card-foreground": "#faf7f5",
        popover: "#231a28",
        "popover-foreground": "#faf7f5",
      },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    description: "High-contrast neon yellow, vivid pink, and cyber cyan",
    isDark: true,
    previewColors: ["#ffee00", "#ff7598", "#2dd4bf", "#111111"],
    colors: {
      light: {
        primary: "#d4b800",
        "primary-foreground": "#000000",
        secondary: "#ff7598",
        "secondary-foreground": "#000000",
        accent: "#0d9488",
        "accent-foreground": "#ffffff",
        background: "#ffffeb",
        foreground: "#1a1a1a",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#0d9488",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#e5df8a",
        input: "#fbf6c7",
        ring: "#d4b800",
        muted: "#f3eed0",
        "muted-foreground": "#5e5840",
        card: "#ffffff",
        "card-foreground": "#1a1a1a",
        popover: "#ffffeb",
        "popover-foreground": "#1a1a1a",
      },
      dark: {
        primary: "#ffee00",
        "primary-foreground": "#000000",
        secondary: "#ff7598",
        "secondary-foreground": "#000000",
        accent: "#2dd4bf",
        "accent-foreground": "#000000",
        background: "#111111",
        foreground: "#ffee00",
        destructive: "#ff5555",
        "destructive-foreground": "#000000",
        success: "#2dd4bf",
        "success-foreground": "#000000",
        warning: "#ffaa00",
        "warning-foreground": "#000000",
        info: "#00ddff",
        "info-foreground": "#000000",
        border: "#ffee00",
        input: "#222222",
        ring: "#ffee00",
        muted: "#222218",
        "muted-foreground": "#b3aa00",
        card: "#1a1a1a",
        "card-foreground": "#ffee00",
        popover: "#111111",
        "popover-foreground": "#ffee00",
      },
    },
  },
  {
    id: "synthwave",
    name: "Synthwave",
    description: "80s retro neon purple background with hot pink and electric cyan",
    isDark: true,
    previewColors: ["#e779c1", "#58c7f3", "#f3cc30", "#1a103c"],
    colors: {
      light: {
        primary: "#d946ef",
        "primary-foreground": "#ffffff",
        secondary: "#0284c7",
        "secondary-foreground": "#ffffff",
        accent: "#eab308",
        "accent-foreground": "#000000",
        background: "#faf5ff",
        foreground: "#1e1035",
        destructive: "#ef4444",
        "destructive-foreground": "#000000",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#ffffff",
        info: "#06b6d4",
        "info-foreground": "#ffffff",
        border: "#e9d5ff",
        input: "#f3e8ff",
        ring: "#d946ef",
        muted: "#ede4f8",
        "muted-foreground": "#665482",
        card: "#ffffff",
        "card-foreground": "#1e1035",
        popover: "#faf5ff",
        "popover-foreground": "#1e1035",
      },
      dark: {
        primary: "#e779c1",
        "primary-foreground": "#1a103c",
        secondary: "#58c7f3",
        "secondary-foreground": "#1a103c",
        accent: "#f3cc30",
        "accent-foreground": "#1a103c",
        background: "#1a103c",
        foreground: "#f3e8ff",
        destructive: "#ff5757",
        "destructive-foreground": "#000000",
        success: "#2dd4bf",
        "success-foreground": "#1a103c",
        warning: "#f3cc30",
        "warning-foreground": "#1a103c",
        info: "#58c7f3",
        "info-foreground": "#1a103c",
        border: "#3b266e",
        input: "#291b54",
        ring: "#e779c1",
        muted: "#2d1c5b",
        "muted-foreground": "#b8a5e0",
        card: "#24184c",
        "card-foreground": "#f3e8ff",
        popover: "#1a103c",
        "popover-foreground": "#f3e8ff",
      },
    },
  },
  {
    id: "retro",
    name: "Retro",
    description: "Nostalgic warm cream, terracotta primary, sage secondary, and warm gold",
    isDark: false,
    previewColors: ["#ef9995", "#a4cbb4", "#ebdc99", "#ece3ca"],
    colors: {
      light: {
        primary: "#ef9995",
        "primary-foreground": "#282425",
        secondary: "#a4cbb4",
        "secondary-foreground": "#282425",
        accent: "#ebdc99",
        "accent-foreground": "#282425",
        background: "#ece3ca",
        foreground: "#282425",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#65a30d",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#d5c79e",
        input: "#ded1a9",
        ring: "#ef9995",
        muted: "#dcd0aa",
        "muted-foreground": "#574e44",
        card: "#e4d8b4",
        "card-foreground": "#282425",
        popover: "#ece3ca",
        "popover-foreground": "#282425",
      },
      dark: {
        primary: "#ef9995",
        "primary-foreground": "#282425",
        secondary: "#a4cbb4",
        "secondary-foreground": "#282425",
        accent: "#ebdc99",
        "accent-foreground": "#282425",
        background: "#25211e",
        foreground: "#ece3ca",
        destructive: "#f87171",
        "destructive-foreground": "#1a1a1a",
        success: "#a3e635",
        "success-foreground": "#1a1a1a",
        warning: "#fbbf24",
        "warning-foreground": "#1a1a1a",
        info: "#38bdf8",
        "info-foreground": "#1a1a1a",
        border: "#453e39",
        input: "#312c28",
        ring: "#ef9995",
        muted: "#3a3430",
        "muted-foreground": "#bfae99",
        card: "#312c28",
        "card-foreground": "#ece3ca",
        popover: "#25211e",
        "popover-foreground": "#ece3ca",
      },
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "Classic dark violet background with purple, pink, and cyan accents",
    isDark: true,
    previewColors: ["#bd93f9", "#ff79c6", "#44475a", "#282a36"],
    colors: {
      light: {
        primary: "#7c3aed",
        "primary-foreground": "#ffffff",
        secondary: "#db2777",
        "secondary-foreground": "#ffffff",
        accent: "#0891b2",
        "accent-foreground": "#ffffff",
        background: "#f8f7fc",
        foreground: "#282a36",
        destructive: "#f43f5e",
        "destructive-foreground": "#000000",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#ca8a04",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#e2e0ed",
        input: "#f0eef7",
        ring: "#7c3aed",
        muted: "#eae8f3",
        "muted-foreground": "#525770",
        card: "#ffffff",
        "card-foreground": "#282a36",
        popover: "#f8f7fc",
        "popover-foreground": "#282a36",
      },
      dark: {
        primary: "#bd93f9",
        "primary-foreground": "#282a36",
        secondary: "#ff79c6",
        "secondary-foreground": "#282a36",
        accent: "#44475a",
        "accent-foreground": "#f8f8f2",
        background: "#282a36",
        foreground: "#f8f8f2",
        destructive: "#ff5555",
        "destructive-foreground": "#000000",
        success: "#50fa7b",
        "success-foreground": "#282a36",
        warning: "#f1fa8c",
        "warning-foreground": "#282a36",
        info: "#8be9fd",
        "info-foreground": "#282a36",
        border: "#44475a",
        input: "#383a59",
        ring: "#bd93f9",
        muted: "#44475a",
        "muted-foreground": "#b0b7da",
        card: "#343746",
        "card-foreground": "#f8f8f2",
        popover: "#282a36",
        "popover-foreground": "#f8f8f2",
      },
    },
  },
  {
    id: "nord",
    name: "Nord",
    description: "Arctic cool palette with slate background, frost blue, and polar night darks",
    isDark: true,
    previewColors: ["#88c0d0", "#81a1c1", "#5e81ac", "#2e3440"],
    colors: {
      light: {
        primary: "#5e81ac",
        "primary-foreground": "#ffffff",
        secondary: "#81a1c1",
        "secondary-foreground": "#2e3440",
        accent: "#88c0d0",
        "accent-foreground": "#2e3440",
        background: "#eceff4",
        foreground: "#2e3440",
        destructive: "#bf616a",
        "destructive-foreground": "#000000",
        success: "#a3be8c",
        "success-foreground": "#2e3440",
        warning: "#ebcb8b",
        "warning-foreground": "#2e3440",
        info: "#88c0d0",
        "info-foreground": "#2e3440",
        border: "#d8dee9",
        input: "#e5e9f0",
        ring: "#5e81ac",
        muted: "#d8dee9",
        "muted-foreground": "#4c566a",
        card: "#e5e9f0",
        "card-foreground": "#2e3440",
        popover: "#eceff4",
        "popover-foreground": "#2e3440",
      },
      dark: {
        primary: "#88c0d0",
        "primary-foreground": "#2e3440",
        secondary: "#81a1c1",
        "secondary-foreground": "#2e3440",
        accent: "#5e81ac",
        "accent-foreground": "#eceff4",
        background: "#2e3440",
        foreground: "#eceff4",
        destructive: "#bf616a",
        "destructive-foreground": "#000000",
        success: "#a3be8c",
        "success-foreground": "#2e3440",
        warning: "#ebcb8b",
        "warning-foreground": "#2e3440",
        info: "#88c0d0",
        "info-foreground": "#2e3440",
        border: "#4c566a",
        input: "#3b4252",
        ring: "#88c0d0",
        muted: "#434c5e",
        "muted-foreground": "#b4c2d6",
        card: "#3b4252",
        "card-foreground": "#eceff4",
        popover: "#2e3440",
        "popover-foreground": "#eceff4",
      },
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Deep earthy woodland dark background with fresh emerald and forest green",
    isDark: true,
    previewColors: ["#1eb854", "#1fd65f", "#243328", "#171212"],
    colors: {
      light: {
        primary: "#15803d",
        "primary-foreground": "#ffffff",
        secondary: "#16a34a",
        "secondary-foreground": "#ffffff",
        accent: "#86efac",
        "accent-foreground": "#14532d",
        background: "#f0fdf4",
        foreground: "#14532d",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#bbf7d0",
        input: "#dcfce7",
        ring: "#15803d",
        muted: "#dcfce7",
        "muted-foreground": "#2d6a4f",
        card: "#ffffff",
        "card-foreground": "#14532d",
        popover: "#f0fdf4",
        "popover-foreground": "#14532d",
      },
      dark: {
        primary: "#1eb854",
        "primary-foreground": "#000000",
        secondary: "#1fd65f",
        "secondary-foreground": "#000000",
        accent: "#243328",
        "accent-foreground": "#ebfaef",
        background: "#171212",
        foreground: "#ebfaef",
        destructive: "#f43f5e",
        "destructive-foreground": "#000000",
        success: "#1eb854",
        "success-foreground": "#000000",
        warning: "#f59e0b",
        "warning-foreground": "#000000",
        info: "#06b6d4",
        "info-foreground": "#000000",
        border: "#2f2727",
        input: "#231c1c",
        ring: "#1eb854",
        muted: "#282020",
        "muted-foreground": "#9ab59f",
        card: "#1f1919",
        "card-foreground": "#ebfaef",
        popover: "#171212",
        "popover-foreground": "#ebfaef",
      },
    },
  },
  {
    id: "aqua",
    name: "Aqua",
    description: "Deep marine ocean background with electric cyan and sky blue accents",
    isDark: true,
    previewColors: ["#09ecf3", "#70a6ff", "#134074", "#0b2545"],
    colors: {
      light: {
        primary: "#0284c7",
        "primary-foreground": "#ffffff",
        secondary: "#38bdf8",
        "secondary-foreground": "#0b2545",
        accent: "#bae6fd",
        "accent-foreground": "#0369a1",
        background: "#f0f9ff",
        foreground: "#0c4a6e",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#bae6fd",
        input: "#e0f2fe",
        ring: "#0284c7",
        muted: "#e0f2fe",
        "muted-foreground": "#1e6080",
        card: "#ffffff",
        "card-foreground": "#0c4a6e",
        popover: "#f0f9ff",
        "popover-foreground": "#0c4a6e",
      },
      dark: {
        primary: "#09ecf3",
        "primary-foreground": "#0b2545",
        secondary: "#70a6ff",
        "secondary-foreground": "#0b2545",
        accent: "#09ecf3",
        "accent-foreground": "#0b2545",
        background: "#0b2545",
        foreground: "#eef4f8",
        destructive: "#ff5757",
        "destructive-foreground": "#000000",
        success: "#00e676",
        "success-foreground": "#0b2545",
        warning: "#ffeb3b",
        "warning-foreground": "#0b2545",
        info: "#09ecf3",
        "info-foreground": "#0b2545",
        border: "#134074",
        input: "#113866",
        ring: "#09ecf3",
        muted: "#133860",
        "muted-foreground": "#9ec3e6",
        card: "#13315c",
        "card-foreground": "#eef4f8",
        popover: "#0b2545",
        "popover-foreground": "#eef4f8",
      },
    },
  },
  {
    id: "valentine",
    name: "Valentine",
    description: "Romantic blush theme with soft pink background, rose pink, and lavender",
    isDark: false,
    previewColors: ["#e96d7b", "#a991f7", "#88dbdd", "#f0d6e8"],
    colors: {
      light: {
        primary: "#e96d7b",
        "primary-foreground": "#ffffff",
        secondary: "#a991f7",
        "secondary-foreground": "#ffffff",
        accent: "#88dbdd",
        "accent-foreground": "#291e25",
        background: "#f0d6e8",
        foreground: "#632c3b",
        destructive: "#f43f5e",
        "destructive-foreground": "#000000",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#ffffff",
        info: "#06b6d4",
        "info-foreground": "#ffffff",
        border: "#deb0cf",
        input: "#ebd0e2",
        ring: "#e96d7b",
        muted: "#e4c0d7",
        "muted-foreground": "#6f3546",
        card: "#e8c4dc",
        "card-foreground": "#632c3b",
        popover: "#f0d6e8",
        "popover-foreground": "#632c3b",
      },
      dark: {
        primary: "#f472b6",
        "primary-foreground": "#371b26",
        secondary: "#c084fc",
        "secondary-foreground": "#371b26",
        accent: "#67e8f9",
        "accent-foreground": "#371b26",
        background: "#2a1523",
        foreground: "#fce7f3",
        destructive: "#fb7185",
        "destructive-foreground": "#1f1218",
        success: "#34d399",
        "success-foreground": "#1f1218",
        warning: "#fbbf24",
        "warning-foreground": "#1f1218",
        info: "#38bdf8",
        "info-foreground": "#1f1218",
        border: "#4f2642",
        input: "#381c2f",
        ring: "#f472b6",
        muted: "#422037",
        "muted-foreground": "#d49bbd",
        card: "#381c2f",
        "card-foreground": "#fce7f3",
        popover: "#2a1523",
        "popover-foreground": "#fce7f3",
      },
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Dusk gradient dark background with coral orange, sunset rose, and amber",
    isDark: true,
    previewColors: ["#ff865b", "#fd6f9c", "#f3a683", "#121c2a"],
    colors: {
      light: {
        primary: "#f97316",
        "primary-foreground": "#ffffff",
        secondary: "#f43f5e",
        "secondary-foreground": "#ffffff",
        accent: "#fb923c",
        "accent-foreground": "#ffffff",
        background: "#fff7ed",
        foreground: "#431407",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#fed7aa",
        input: "#ffedd5",
        ring: "#f97316",
        muted: "#ffedd5",
        "muted-foreground": "#803c1d",
        card: "#ffffff",
        "card-foreground": "#431407",
        popover: "#fff7ed",
        "popover-foreground": "#431407",
      },
      dark: {
        primary: "#ff865b",
        "primary-foreground": "#121c2a",
        secondary: "#fd6f9c",
        "secondary-foreground": "#121c2a",
        accent: "#f3a683",
        "accent-foreground": "#121c2a",
        background: "#121c2a",
        foreground: "#f8e9e2",
        destructive: "#ff5757",
        "destructive-foreground": "#000000",
        success: "#2dd4bf",
        "success-foreground": "#121c2a",
        warning: "#fcd34d",
        "warning-foreground": "#121c2a",
        info: "#60a5fa",
        "info-foreground": "#121c2a",
        border: "#273a54",
        input: "#1e2e44",
        ring: "#ff865b",
        muted: "#22344c",
        "muted-foreground": "#9fb3cb",
        card: "#1b293d",
        "card-foreground": "#f8e9e2",
        popover: "#121c2a",
        "popover-foreground": "#f8e9e2",
      },
    },
  },
  {
    id: "coffee",
    name: "Coffee",
    description: "Rich espresso dark background with caramel and warm roasted accents",
    isDark: true,
    previewColors: ["#db924b", "#dc944c", "#94633b", "#20161f"],
    colors: {
      light: {
        primary: "#b45309",
        "primary-foreground": "#ffffff",
        secondary: "#d97706",
        "secondary-foreground": "#ffffff",
        accent: "#fef3c7",
        "accent-foreground": "#78350f",
        background: "#fdfbf7",
        foreground: "#451a03",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#e7dfd5",
        input: "#f5eee6",
        ring: "#b45309",
        muted: "#f5eee6",
        "muted-foreground": "#78411b",
        card: "#ffffff",
        "card-foreground": "#451a03",
        popover: "#fdfbf7",
        "popover-foreground": "#451a03",
      },
      dark: {
        primary: "#db924b",
        "primary-foreground": "#20161f",
        secondary: "#dc944c",
        "secondary-foreground": "#20161f",
        accent: "#db924b",
        "accent-foreground": "#20161f",
        background: "#20161f",
        foreground: "#ddd0b9",
        destructive: "#ef4444",
        "destructive-foreground": "#000000",
        success: "#22c55e",
        "success-foreground": "#20161f",
        warning: "#eab308",
        "warning-foreground": "#20161f",
        info: "#38bdf8",
        "info-foreground": "#20161f",
        border: "#3f2d3d",
        input: "#2d202b",
        ring: "#db924b",
        muted: "#342632",
        "muted-foreground": "#b39f90",
        card: "#2a1e29",
        "card-foreground": "#ddd0b9",
        popover: "#20161f",
        "popover-foreground": "#ddd0b9",
      },
    },
  },
  {
    id: "dim",
    name: "Dim",
    description: "Modern muted charcoal dark background with mint green and slate blue",
    isDark: true,
    previewColors: ["#9fe88d", "#79a7d3", "#ff7ac6", "#2a303c"],
    colors: {
      light: {
        primary: "#16a34a",
        "primary-foreground": "#ffffff",
        secondary: "#2563eb",
        "secondary-foreground": "#ffffff",
        accent: "#db2777",
        "accent-foreground": "#ffffff",
        background: "#f8fafc",
        foreground: "#1e293b",
        destructive: "#ef4444",
        "destructive-foreground": "#000000",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#ffffff",
        info: "#2563eb",
        "info-foreground": "#ffffff",
        border: "#e2e8f0",
        input: "#f1f5f9",
        ring: "#16a34a",
        muted: "#f1f5f9",
        "muted-foreground": "#505f79",
        card: "#ffffff",
        "card-foreground": "#1e293b",
        popover: "#f8fafc",
        "popover-foreground": "#1e293b",
      },
      dark: {
        primary: "#9fe88d",
        "primary-foreground": "#193614",
        secondary: "#79a7d3",
        "secondary-foreground": "#16283b",
        accent: "#ff7ac6",
        "accent-foreground": "#3a1329",
        background: "#2a303c",
        foreground: "#e2e8f0",
        destructive: "#ff6e6e",
        "destructive-foreground": "#2a303c",
        success: "#9fe88d",
        "success-foreground": "#193614",
        warning: "#f3cc30",
        "warning-foreground": "#2a303c",
        info: "#79a7d3",
        "info-foreground": "#16283b",
        border: "#383f4d",
        input: "#222731",
        ring: "#9fe88d",
        muted: "#313846",
        "muted-foreground": "#94a3b8",
        card: "#242933",
        "card-foreground": "#e2e8f0",
        popover: "#2a303c",
        "popover-foreground": "#e2e8f0",
      },
    },
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Premium dark gold theme with deep obsidian background and champagne accents",
    isDark: true,
    previewColors: ["#dca54c", "#e0d8b0", "#ff7598", "#09090b"],
    colors: {
      light: {
        primary: "#b45309",
        "primary-foreground": "#ffffff",
        secondary: "#78350f",
        "secondary-foreground": "#ffffff",
        accent: "#fef3c7",
        "accent-foreground": "#78350f",
        background: "#fafaf9",
        foreground: "#1c1917",
        destructive: "#dc2626",
        "destructive-foreground": "#ffffff",
        success: "#16a34a",
        "success-foreground": "#ffffff",
        warning: "#d97706",
        "warning-foreground": "#ffffff",
        info: "#0284c7",
        "info-foreground": "#ffffff",
        border: "#e7e5e4",
        input: "#f5f5f4",
        ring: "#b45309",
        muted: "#f5f5f4",
        "muted-foreground": "#5f5953",
        card: "#ffffff",
        "card-foreground": "#1c1917",
        popover: "#fafaf9",
        "popover-foreground": "#1c1917",
      },
      dark: {
        primary: "#dca54c",
        "primary-foreground": "#150e04",
        secondary: "#e0d8b0",
        "secondary-foreground": "#150e04",
        accent: "#c28833",
        "accent-foreground": "#ffffff",
        background: "#09090b",
        foreground: "#f5f5f5",
        destructive: "#ef4444",
        "destructive-foreground": "#000000",
        success: "#22c55e",
        "success-foreground": "#09090b",
        warning: "#dca54c",
        "warning-foreground": "#09090b",
        info: "#38bdf8",
        "info-foreground": "#09090b",
        border: "#27272a",
        input: "#1c1c21",
        ring: "#dca54c",
        muted: "#202026",
        "muted-foreground": "#a1a1aa",
        card: "#141418",
        "card-foreground": "#f5f5f5",
        popover: "#09090b",
        "popover-foreground": "#f5f5f5",
      },
    },
  },
  {
    id: "lovably",
    name: "Lovably",
    description:
      "Vibrant magenta and violet gradient aesthetic inspired by lovable.dev with crisp obsidian dark and warm parchment light modes",
    isDark: true,
    previewColors: ["#ff2e7e", "#8b5cf6", "#ff7a45", "#09090b"],
    colors: {
      light: {
        primary: "#ff2e7e",
        "primary-foreground": "#ffffff",
        secondary: "#7c3aed",
        "secondary-foreground": "#ffffff",
        accent: "#ff7a45",
        "accent-foreground": "#ffffff",
        background: "#faf8f5",
        foreground: "#18181b",
        destructive: "#ef4444",
        "destructive-foreground": "#000000",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#ffffff",
        info: "#06b6d4",
        "info-foreground": "#ffffff",
        border: "#e4e4e7",
        input: "#f4f4f5",
        ring: "#ff2e7e",
        muted: "#f4f4f5",
        "muted-foreground": "#71717a",
        card: "#ffffff",
        "card-foreground": "#18181b",
        popover: "#faf8f5",
        "popover-foreground": "#18181b",
      },
      dark: {
        primary: "#ff2e7e",
        "primary-foreground": "#ffffff",
        secondary: "#8b5cf6",
        "secondary-foreground": "#ffffff",
        accent: "#ff7a45",
        "accent-foreground": "#ffffff",
        background: "#09090b",
        foreground: "#f4f4f5",
        destructive: "#f43f5e",
        "destructive-foreground": "#000000",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#f59e0b",
        "warning-foreground": "#09090b",
        info: "#38bdf8",
        "info-foreground": "#09090b",
        border: "#27272a",
        input: "#18181b",
        ring: "#ff2e7e",
        muted: "#1f1f23",
        "muted-foreground": "#a1a1aa",
        card: "#121215",
        "card-foreground": "#f4f4f5",
        popover: "#09090b",
        "popover-foreground": "#f4f4f5",
      },
    },
  },
  {
    id: "hellokitty",
    name: "Hello Kitty",
    description:
      "Playful pastel pink and milk-white theme with ruby red bow and pastel yellow accents",
    isDark: false,
    previewColors: ["#ff7da7", "#ff3366", "#ffd166", "#fff5f8"],
    colors: {
      light: {
        primary: "#ff7da7",
        "primary-foreground": "#ffffff",
        secondary: "#ffb3c6",
        "secondary-foreground": "#2d1520",
        accent: "#ff3366",
        "accent-foreground": "#ffffff",
        background: "#fff5f8",
        foreground: "#2d1520",
        destructive: "#f43f5e",
        "destructive-foreground": "#000000",
        success: "#10b981",
        "success-foreground": "#ffffff",
        warning: "#ffd166",
        "warning-foreground": "#2d1520",
        info: "#38bdf8",
        "info-foreground": "#ffffff",
        border: "#ffd6e0",
        input: "#fae8ee",
        ring: "#ff7da7",
        muted: "#fae8ee",
        "muted-foreground": "#804a60",
        card: "#ffffff",
        "card-foreground": "#2d1520",
        popover: "#fff5f8",
        "popover-foreground": "#2d1520",
      },
      dark: {
        primary: "#ff6599",
        "primary-foreground": "#1f0e16",
        secondary: "#ff9ebb",
        "secondary-foreground": "#1f0e16",
        accent: "#ff3366",
        "accent-foreground": "#ffffff",
        background: "#1f141a",
        foreground: "#fff0f5",
        destructive: "#fb7185",
        "destructive-foreground": "#1f0e16",
        success: "#34d399",
        "success-foreground": "#1f0e16",
        warning: "#ffd166",
        "warning-foreground": "#1f0e16",
        info: "#38bdf8",
        "info-foreground": "#1f0e16",
        border: "#3d2130",
        input: "#2a1923",
        ring: "#ff6599",
        muted: "#331c2a",
        "muted-foreground": "#c798ad",
        card: "#2a1923",
        "card-foreground": "#fff0f5",
        popover: "#1f141a",
        "popover-foreground": "#fff0f5",
      },
    },
  },
];

const BY_ID = new Map(THEME_PRESETS.map((preset) => [preset.id.toLowerCase(), preset]));

/**
 * `TendrilThemes.GetTheme(id)`: an unknown or blank id resolves to the default rather than throwing,
 * because `config.yaml` is hand-editable and a typo there must not leave the app unstyled.
 */
export function getThemePreset(id: string | null | undefined): ThemePreset {
  const found = id ? BY_ID.get(id.trim().toLowerCase()) : undefined;
  return found ?? BY_ID.get(DEFAULT_THEME_PRESET_ID)!;
}

/**
 * The stylesheet a preset installs: one block for its light colours and one for its dark ones, which is
 * how `tokens.css` itself is arranged. Both are emitted, so the preset survives a theme-mode change and
 * a system `prefers-color-scheme` flip without being re-applied.
 *
 * The selectors are deliberately *more specific* than `tokens.css`'s `:root` and `.dark` rather than
 * merely later in the document: a lazily-loaded chunk's stylesheet is appended when its view first
 * renders, so an override that relied on document order would lose the moment one of those chunks
 * carried the token block. `:root:root` outranks `:root` and `.dark`; `html.dark:root` outranks both
 * and this rule's own light half.
 *
 * The default preset generates nothing at all - see the module note.
 */
export const LIGHT_SELECTOR = ":root:root";
export const DARK_SELECTOR = "html.dark:root";

export function themePresetCss(preset: ThemePreset): string {
  const block = (selector: string, colors: ThemePresetColors | undefined): string => {
    if (!colors) return "";
    const body = Object.entries(colors)
      .map(([token, value]) => `  --${token}: ${value};`)
      .join("\n");
    return body === "" ? "" : `${selector} {\n${body}\n}`;
  };

  return [block(LIGHT_SELECTOR, preset.colors.light), block(DARK_SELECTOR, preset.colors.dark)]
    .filter((part) => part !== "")
    .join("\n");
}

/**
 * Applies a preset, mirroring `TendrilThemes.ApplyTheme(client, themeId)`.
 *
 * The generated CSS goes into one `<style>` element appended to `<head>`, so it wins over
 * `tokens.css` on document order at equal specificity, and switching preset replaces its contents
 * rather than accumulating layers. Returns the preset that actually applied, which is the default for
 * an id nothing matches.
 */
export function applyThemePreset(
  id: string | null | undefined,
  doc: Document | undefined = typeof document === "undefined" ? undefined : document,
): ThemePreset {
  const preset = getThemePreset(id);
  if (!doc) return preset;

  const css = themePresetCss(preset);
  const existing = doc.getElementById(THEME_PRESET_STYLE_ID);

  if (css === "") {
    existing?.remove();
    return preset;
  }

  const style = existing ?? doc.createElement("style");
  if (!existing) {
    style.id = THEME_PRESET_STYLE_ID;
    doc.head.appendChild(style);
  }
  style.textContent = css;
  return preset;
}
